window.BITBLOC = {
  products: [
    {
      id: "gecko-bot",
      name: "GeckoBot X1",
      tagline: "Robô modular programável com sensores e app",
      description:
        "Monta o chassi, encaixa sensores e programa missões pelo app BitLab. Ideal pra quem quer robótica de verdade sem kit infantil.",
      price: 489.9,
      oldPrice: 549.9,
      category: "robotica",
      accent: "yellow",
      age: "14+",
      rating: 4.8,
      reviews: 126,
      stock: 18,
      badges: ["Mais vendido", "App incluso"],
      specs: ["Bluetooth 5.2", "6 sensores", "Blocos magnéticos", "App iOS/Android"],
      featured: true,
    },
    {
      id: "skybloc-fpv",
      name: "SkyBloc FPV",
      tagline: "Drone de corrida com câmera HD e óculos VR",
      description:
        "Frame em fibra, motores brushless e feed FPV de baixa latência. Do modo iniciante à pista indoor em minutos.",
      price: 1299.0,
      category: "drones",
      accent: "blue",
      age: "16+",
      rating: 4.7,
      reviews: 64,
      stock: 7,
      badges: ["FPV Pro", "Estoque baixo"],
      specs: ["Câmera 1080p", "Óculos incluso", "Modo GPS", "Bateria 25min"],
    },
    {
      id: "circuit-cube",
      name: "Circuit Cube Pro",
      tagline: "Cubo LED 8×8 com efeitos e API aberta",
      description:
        "Animações, visualizer de áudio e SDK aberto. Encaixa no setup gamer ou vira peça de mesa interativa.",
      price: 249.9,
      category: "gadgets",
      accent: "silver",
      age: "12+",
      rating: 4.6,
      reviews: 210,
      stock: 42,
      badges: ["API aberta"],
      specs: ["512 LEDs", "USB-C", "SDK JS/Python", "Microfone embutido"],
    },
    {
      id: "maker-kit",
      name: "Maker Bloc Kit",
      tagline: "Kit DIY Arduino com 40 projetos guiados",
      description:
        "Protoboard, sensores, LEDs e apostila digital. Do blink ao IoT caseiro com passo a passo em português.",
      price: 319.0,
      oldPrice: 359.0,
      category: "diy",
      accent: "yellow",
      age: "13+",
      rating: 4.9,
      reviews: 301,
      stock: 55,
      badges: ["Iniciante+", "40 projetos"],
      specs: ["Placa compatível Uno", "120+ peças", "Guia PDF", "Cabos inclusos"],
      featured: true,
    },
    {
      id: "pulse-pad",
      name: "Pulse Pad RGB",
      tagline: "Controlador MIDI portátil para beats e live",
      description:
        "16 pads sensíveis, modos de scale e RGB reativo. Plug-and-play com DAWs e apps mobile.",
      price: 599.0,
      category: "gadgets",
      accent: "blue",
      age: "15+",
      rating: 4.5,
      reviews: 88,
      stock: 23,
      badges: ["MIDI", "RGB"],
      specs: ["16 pads", "USB MIDI", "Bateria 8h", "Modo standalone"],
    },
    {
      id: "volt-racer",
      name: "Volt Racer S",
      tagline: "Carrinho RC brushless com telemetria ao vivo",
      description:
        "Chassis tuning, telemetria no celular e modo drift. Para quem quer RC com cara de engenharia, não brinquedo de prateleira.",
      price: 879.0,
      category: "robotica",
      accent: "silver",
      age: "14+",
      rating: 4.7,
      reviews: 53,
      stock: 11,
      badges: ["Brushless"],
      specs: ["Motor 3650", "Telemetria app", "4WD", "Bateria LiPo"],
    },
    {
      id: "neon-drone-mini",
      name: "Neon Drone Mini",
      tagline: "Mini drone indoor com luzes reativas",
      description:
        "Leve, resistente a batidas leves e com modos de voo assistido. Perfeito pra treinar FPV em quarto ou sala.",
      price: 429.0,
      category: "drones",
      accent: "yellow",
      age: "14+",
      rating: 4.4,
      reviews: 97,
      stock: 30,
      badges: ["Indoor"],
      specs: ["Peso 85g", "Prop guards", "LED neon", "Controle + app"],
    },
    {
      id: "solder-lab",
      name: "Solder Lab Desk",
      tagline: "Estação DIY com ferro, suporte e PCB starter",
      description:
        "Kit de bancada pra soldar com segurança: ferro temperatura fixa, sugador, flux e 3 PCBs de treino.",
      price: 279.0,
      category: "diy",
      accent: "blue",
      age: "15+",
      rating: 4.8,
      reviews: 142,
      stock: 19,
      badges: ["Bancada"],
      specs: ["Ferro 60W", "3 PCBs treino", "Sugador", "Óculos incluso"],
    },
    {
      id: "bit-watch",
      name: "BitWatch Hack",
      tagline: "Smartwatch open firmware pra customizar",
      description:
        "Tela colorida, sensores e firmware aberto. Troca faces, apps e faz integrações BLE do seu jeito.",
      price: 699.0,
      oldPrice: 749.0,
      category: "gadgets",
      accent: "silver",
      age: "15+",
      rating: 4.3,
      reviews: 41,
      stock: 14,
      badges: ["Open FW"],
      specs: ["BLE 5", "SpO2 + HR", "7 dias bateria", "SDK open"],
    },
  ],
  categories: [
    {
      id: "robotica",
      title: "Robótica",
      description: "Monta, programa e compete com máquinas que realmente se mexem.",
    },
    {
      id: "drones",
      title: "Drones & FPV",
      description: "Voe com precisão — da primeira decolagem à corrida indoor.",
    },
    {
      id: "diy",
      title: "Kits DIY",
      description: "Solda, prototipa e cria gadgets do zero com peças de verdade.",
    },
    {
      id: "gadgets",
      title: "Gadgets",
      description: "Brinquedos smart para mesa, setup e performances.",
    },
  ],
  faqs: [
    {
      q: "Isso é brinquedo de criança?",
      a: "Não. A BitBloc é pensada para adolescentes e adultos makers — hardware real, documentação técnica e upgrades.",
    },
    {
      q: "Preciso saber programar?",
      a: "Não no dia 1. Kits como Maker Bloc e GeckoBot têm modo guiado; depois você abre o código e a API.",
    },
    {
      q: "Qual o prazo de envio?",
      a: "Pedidos em estoque saem em até 1 dia útil. Entrega Brasil em média de 3 a 7 dias úteis.",
    },
    {
      q: "Tem garantia?",
      a: "Sim: 12 meses contra defeito de fabricação, com suporte técnico por e-mail e Discord da comunidade.",
    },
  ],
  reviews: [
    {
      name: "Lara M.",
      age: "17",
      text: "Montamos o GeckoBot no clube de robótica. Sensores de verdade, não plaquinha de faz-de-conta.",
    },
    {
      name: "Diego R.",
      age: "24",
      text: "O Maker Kit salvou meu fim de semana. Do blink ao IoT em um sábado.",
    },
    {
      name: "Nina K.",
      age: "19",
      text: "SkyBloc FPV é viciante. Modo iniciante ajuda, mas o teto é alto pra quem quer correr.",
    },
  ],
};
